import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>zeros next.js home !!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="zeros-park의 home페이지 title, og:title" />
        <meta property="og:description" content="zeros-park의 home페이지 title, og:desc" />
        <meta property="og:image" content="/asset/img/testimg1.png" />
        <meta property="twitter:title" content="zeros-park의 home페이지 title, twit:title" />
        <meta property="twitter:description" content="zeros-park의 home페이지 title, twit:desc" />
        <meta property="twitter:image" content="/asset/img/testimg2.png" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <Cards />
      </Main>
    </Container>
  )
}
